apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-gateway
  namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-checkout
  namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pricing
  namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-inventory
  namespace: ecommerce
automountServiceAccountToken: false
