server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  location = /api/arch {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '{"arch":"kubernetes-nanoservices-checkout","component":"gateway"}';
  }

  location = /api/ping {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '{"ok":true}';
  }

  location = /api/checkout {
    proxy_pass http://checkout-svc/checkout;
  }
}
