server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  location = /api/arch {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '{"arch":"nanoservices-compose-k8s","component":"gateway"}';
  }

  location = /api/ping {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '{"ok":true}';
  }

  location = /api/checkout {
    proxy_set_header X-Request-Id $http_x_request_id;
    proxy_set_header Content-Type application/json;
    proxy_pass http://checkout-fn:3003/checkout;
  }
}
